#!/usr/bin/env node

const config = require('../config');
const del = require('del');
const colors = require('colors');

del([config.favicon.build, `${config.paths.build}/browserconfig.xml`, `${config.paths.build}/manifest.json`, `${config.paths.build}/manifest.webapp`]).then(paths => {
  console.log(colors.green('Favicon files cleaned.'));
});
