#!/usr/bin/env node

const config = require('../config');
const favicons = require('favicons');
const colors = require('colors');
const path = require('path');
const fs = require('fs-extra');
const del = require('del');

del.sync([config.favicons.build]);
fs.mkdirSync(config.favicons.build);

favicons(config.favicons.source, {
  appName: config.name,
  appDescription: config.description,
  developerName: null,
  developerURL: null,
  background: 'transparent',
  theme_color: '#ffffff',
  path: config.favicons.path,
  display: 'standalone',
  orientation: 'portrait',
  version: config.version,
  logging: false,
  online: false,
  icons: {
    android: true,
    appleIcon: true,
    appleStartup: true,
    coast: true,
    favicons: true,
    firefox: true,
    opengraph: false,
    twitter: false,
    windows: true,
    yandex: false,
  },
  html: config.favicons.html,
  replace: true,
}, function (error, response) {
  if (error) return console.error(error);

  const { images, files, html } = response;
  if(config.favicons.html) {
     fs.writeFileSync(config.favicons.html, html.join('\n').replace(/assets/g, '{{assets}}'));
  }
  const promises = [];
  promises.push(images.map(writeImage));
  promises.push(files.map(writeFile));

  Promise.all(promises).then(() => {
    console.log(colors.green('Favicons generated.'));
  });
});

function writeImage({ name, contents }) {
  return new Promise((resolve, reject) => {
    const full = path.join(config.favicons.build, name);

    fs.writeFile(full, contents, (error) => {
      if (error) return reject(error);
      resolve();
    })
  })
}
function writeFile({ name, contents }) {
  return new Promise((resolve, reject) => {
    const full = path.join(config.favicons.root, name);

    fs.writeFile(full, contents, (error) => {
      if (error) return reject(error);
      resolve();
    })
  })
}